
#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: 2.0
fosses:
  - product_number: CTX1031249
    license: Apache-2.0
    obligation: |
      "Including the full license text in a prominent place with the software when the FOSS is distributed.
      This fulfills the following: Ericsson must give any recipients of the software a copy of the Apache License.
      Ericsson must cause any modified files to carry prominent notices stating that Ericsson changed the files.
      In any source form Ericsson distributes, all copyright, patent, trademark and attribution notices must be retained.
      If the software includes a NOTICE text file as part of its distribution,
      then any derivative work Ericsson distributes must include a readable copy of the attribution notices contained within such NOTICE file."
    usage: |
      "Workflow engine for Kubernetes"